config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  resources :categories do 
    resources :products
  end
  
  root 'categories#index'


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit show update destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  # before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]


  
  def index
    @categories = Category.all
    # @user_email = current_user.email if user_signed_in?

    # render json: @categories, only: [:name ]
  end
  


  

  # GET /categories/1 or /categories/1.json
  def show
  @category = Category.find(params[:id])
  @products = @category.products
  # render json: @category
  end

  # GET /categories/new
  def new

    @category = Category.new
    # render json: @category, only: [:name ]

  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def authorize_admin
      redirect_to root_path, alert: 'You do not have permission.' unless current_user.admin?
    end

    
    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category, only: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  # before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]


  # GET /products or /products.json
  def index
    @products = Product.all
    @products = @category.products
    #  render json: @products, only: [:id, :title, :image, :price, :category_id]

  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  
    # Assuming you have a `category_id` column in your `products` table
    category_id = @product.category_id
    
    # Ensure that category_id is present before attempting to find the category
    if category_id.present?
      @category = Category.find(category_id)
    else
      # Handle the case where the category is not found
      render json: { error: 'Category not found.' }, status: :not_found
      return
    end
  
    # render json: {
    #   id: @product.id,
    #   title: @product.title,
    #   image: @product.image,
    #   price: @product.price,
    #   category_id: @product.category_id,
    #   category: @category.as_json(only: [:id, :name]) # Include category information if needed
    # }
  end
  
  # GET /products/new
  def new
    @product=  Product.new
    #  render json: @products, only: [:id, :title, :image, :price, :category_id]

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @category = @product.category
    @product.destroy

    redirect_to category_products_path(@category), notice: 'Product was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id].present?
  end
  

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def authorize_admin
      unless current_user.admin?
        flash[:alert] = 'You do not have permission to access this page.'
        redirect_back fallback_location: root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :image, :price, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to 'All Products', category_products_path(@category) %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

<div>
  <strong>Category:</strong> <%= @category.name %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newcategory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :information, style: "display: block" %>
    <%= form.text_field :information %>
  </div>

  <div>
    <%= form.label :category %>
    <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id]})%>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= product.image %>
  </p>

  <p>
    <strong>Information:</strong>
    <%= product.information %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>


<h2>All products</h2>
<% @products.each do |product| %>
  <%= link_to product.title, category_product_path(@category, product) %><br>
<% end %>

<div id="products">
  <% @products.each do |product| %>
      <%= link_to product.title, category_product_path(@category, product) %><br>


    <%= render product %>
    <p>
      <%= link_to "Show this product",  category_product_path(@category, product) %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @product %>
<%= link_to 'All Products', category_products_path(@category) %>


<h2><%= @product.title %></h2>
<p><%= @product.price %></p>
<p><%= @product.image %></p>



<div>
<%= link_to "Edit this product", edit_category_product_path(@product.category, @product) %> |
  <%= link_to "Back to products", category_products_path(@category) %>

<%= button_to "Destroy this product", category_product_path(@category, @product), method: :delete, data: { confirm: "Are you sure?" } %>
</div>